### ISSUE TITLE
Hardcoded framework path

### ISSUE THREAD

**Issue by Hais** [rockbruno/SwiftInfo#1]
Interesting project! 
However, using 0.1.0 throws the error: 
```
./Pods/SwiftInfo/swiftinfo
SwiftInfo
dyld: Library not loaded: /Users/bruno.rocha/Desktop/PersonalCodes/SwiftInfo/.build/x86_64-apple-macosx10.10/release/libSwiftInfoCore.dylib
  Referenced from: /Users/hais/workspace/ios/./Infofile
  Reason: image not found
```

**Comment by rockbruno** [comment]
Hi Hais, thanks for that!
What the hell? That's not in the code, SPM did that... I think I'm not building it correctly then, I'll run some tests and update the Pod once I figure it out

**Comment by rockbruno** [comment]
Okay, I think I figured it out, it turns out that SPM really hardcodes the search paths when you export libraries. The following worked for me, can you try this out?
```
cd {the place where the binary + libraries are}
install_name_tool -id "@loader_path/libSwiftInfoCore.dylib" libSwiftInfoCore.dylib
./swiftinfo (need to run it from the same folder)
```

I'll find the path that makes it work regardless of where you are and push a new build.

**Comment by rockbruno** [comment]
0.1.1 should do the trick for now! I'm forcing the tool to update the search paths before running the Infofile.

**Comment by Hais** [comment]
Hi @rockbruno. I can confirm 0.1.1 solves this issue. I look forward to giving it a try now 👍
