### ISSUE TITLE
Errors after installing via Mint (SwiftPM)

### ISSUE THREAD

**Issue by Dschee** [rockbruno/SwiftInfo#14]
I just installed SwiftInfo via [Mint](https://github.com/yonaskolb/Mint) (by running `mint install rockbruno/SwiftInfo swiftinfo`) and installation succeeded. But when I now try to run `swiftinfo`, I just get this error:

```bash
* SwiftInfo
<unknown>:0: error: module map file '/usr/local/bin/Csourcekitd/include/module.modulemap' not found
<unknown>:0: error: module map file '/usr/local/bin/Csourcekitd/include/module.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'
```

Here's my `Infofile.swift` contents:

```swift
import SwiftInfoCore

FileUtils.buildLogFilePath = "./build/build_log/App-Development.log"
FileUtils.testLogFilePath = "./build/tests_log/App-Development.log"

let projectInfo = ProjectInfo(xcodeproj: "NewProjectTemplate.xcodeproj", target: "App", configuration: "Development")
let api = SwiftInfo(projectInfo: projectInfo)

let output = [
    api.extract(IPASizeProvider.self),
    api.extract(WarningCountProvider.self),
    api.extract(TestCountProvider.self),
    api.extract(TargetCountProvider.self),
    api.extract(CodeCoverageProvider.self),
    api.extract(LinesOfCodeProvider.self)
].joined()

// Save the output to disk.
api.save(output: output)
```

I'm running `swiftinfo` on macOS 10.14.4 with Swift 5.0.1 & Xcode 10.2.1.

**Comment by rockbruno** [comment]
SwiftPM isn't supported. This is because I need to provide additional files for SourceKit which SwiftPM can't do natively.

**Comment by Dschee** [comment]
It's sad that installtion via SwiftPM isn't supported. But maybe we can add a Makefile and support installation via Homebrew instead? I've just opened an issue for that: #17

**Comment by rockbruno** [comment]
I can support SwiftPM if I get rid of SourceKit. I currently don't do anything with it but it could be useful in the future 😢 It's just that SwiftPM doesn't let me ship additional files with the binary, that's the only reason.

**Comment by Dschee** [comment]
What files do you need to ship with the binary? Maybe there's some kind of workaround?

**Comment by rockbruno** [comment]
The tool manually runs `swiftc` to be able to read the Infofile, and because I support SourceKit (a C library) I need to link a modulemap file. I can't make SwiftPM copy this, so I ship it as a .zip with CocoaPods.
