### ISSUE TITLE
Installation via CocoaPods unclear

### ISSUE THREAD

**Issue by Jeehut** [rockbruno/SwiftInfo#15]
After failing to properly install SwiftInfo via SwiftPM/Mint (see #14), I wanted to try the "official" way of installing it, but I failed. I'm used to using CocoaPods for installing iOS project dependencies, but I've moved away from CocoaPods and I'm not using it any more. How can I use CocoaPods just for installing SwiftInfo now? 

Do I really need to configure a CocoaPods target and list SwiftInfo in there? I mean, that has many side effects, including the creation of a Workspace, which I don't need. Also, the executable is saved to the path `../Pods/SwiftInfo/swiftinfo` which is much less easy to type or remember than simply `swiftinfo`. 

A more detailed installation section would help a lot!

**Comment by rockbruno** [comment]
[You can manually download the release](https://github.com/rockbruno/SwiftInfo/releases) if you don't want to use CocoaPods. Just unzip the contents in a folder inside your project and you should be good to go.

**Comment by Dschee** [comment]
Thanks for the pointer, I will use it next time. But if that's a recommended way of installing SwiftInfo, the README should mention it and maybe even contain a link to the latest release.

**Comment by rockbruno** [comment]
Will do, thanks for the tip!
