### ISSUE TITLE
Missing usage instructions without Fastlane

### ISSUE THREAD

**Issue by Jeehut** [rockbruno/SwiftInfo#16]
To me it is unclear how I can use SwiftInfo. After installing it via CocoaPods and running `Pods/SwiftInfo/swiftinfo` I get the following output:

```bash
* SwiftInfo
* Extracting ipa_size
* **ipa_size:** The folder “build” doesn’t exist.
* Extracting warning_count
* **warning_count:**     Build log not found!
    Expected path:
    Thrown error: The file “NewProjectTemplate-iOS” couldn’t be opened because you don’t have permission to view it.
* Extracting test_count
* **test_count:**     Test log not found!
    Expected path:
    Thrown error: The file “NewProjectTemplate-iOS” couldn’t be opened because you don’t have permission to view it.
* Extracting target_count
* **target_count:**     Build log not found!
    Expected path:
    Thrown error: The file “NewProjectTemplate-iOS” couldn’t be opened because you don’t have permission to view it.
* Extracting code_coverage
* **code_coverage:**     Test log not found!
    Expected path:
    Thrown error: The file “NewProjectTemplate-iOS” couldn’t be opened because you don’t have permission to view it.
* Extracting lines_of_code
* **lines_of_code:**     Test log not found!
    Expected path:
    Thrown error: The file “NewProjectTemplate-iOS” couldn’t be opened because you don’t have permission to view it.
* Saving output to disk
* Fatal error: Failed to load plist ./$(SRCROOT)/App/SupportingFiles/Info.plist
```

Here's my `Infofile.swift` contents:

```swift
import SwiftInfoCore

let projectInfo = ProjectInfo(xcodeproj: "NewProjectTemplate.xcodeproj", target: "App", configuration: "Development")
let api = SwiftInfo(projectInfo: projectInfo)

let output =
    api.extract(IPASizeProvider.self) +
    api.extract(WarningCountProvider.self) +
    api.extract(TestCountProvider.self) +
    api.extract(TargetCountProvider.self) +
    api.extract(CodeCoverageProvider.self) +
    api.extract(LinesOfCodeProvider.self)

// Save the output to disk.
api.save(output: output)
```

And this is the project I'm trying to configure this with:
https://github.com/JamitLabs/NewProjectTemplate-iOS

I will now try to find the correct paths and specify them, but having some hints in the README and maybe an example provided without Fastlane would make usage much easier.

**Comment by rockbruno** [comment]
You need to add the path to your build/test logs in your Infofile. This is shown in the README example:
```
FileUtils.buildLogFilePath = "./build/build_log/MyApp-MyConfig.log"
FileUtils.testLogFilePath = "./build/tests_log/MyApp-MyConfig.log"
```
Fastlane can provide these logs (in the README as well). Given that IPA extraction failed, it looks like you tried to run this tool before running fastlane. It extracts info from the build artifacts, so it only works after you archive a build. You can make this work without fastlane, but I'm yet to see someone that manually runs xcodebuild/xctest which is why this info is missing. I might use it for the example project.

I'm in the process of providing an example project, but it's a bit complicated because I can't just provide the logs, it needs to be build from the user's machine. Will be done soon though

**Comment by Dschee** [comment]
Hey, thanks for the quick answer.

Just one note: I'm not running `xcodebuild` or `xctest` myself at all, and I don't want to. I'm using the Xcode GUI for everything and would just like to use SwiftInfo to print out information when I'm interested in that, which doesn't necessarily have to be the CI, I might want to have a look myself, e.g. in a after-commit hook or by manually running `swiftinfo`. Just to explain the usage situation.

**Comment by rockbruno** [comment]
Ah I see. I'm not sure if it's possible to use this tool by building with Xcode's GUI because I need the build's raw logs... If someone finds a way to tell Xcode to put the logs somewhere, then it would work 😄
