### ISSUE TITLE
Support installation via Homebrew

### ISSUE THREAD

**Issue by Jeehut** [rockbruno/SwiftInfo#17]
Currently the only way to install SwiftInfo is via CocoaPods which is weird in projects, that don't use CocoaPods. Therfore I suggest we add a Makefile and prepare a Homebrew tap so SwiftInfo can be installed via Homebrew. Here's a good article to get started:
https://nshipster.com/homebrew/

**Comment by rockbruno** [comment]
This is a good idea! If this works I might even deprecate the cocoapods install :)
