### ISSUE TITLE
configuration without infofile

### ISSUE THREAD

**Issue by rnkyr** [rockbruno/SwiftInfo#25]
Hey,

First of all - thanks for the library, it's really helpful!

I've searched through the doc and sources and it looks like there's no way to configure the tool without Infofile.swift

It would be really great if you add such support (for example through CLI args) because Infofile contains some dynamic data (like webhook URL and configuration). When running with fastlane we could simply pass it and it'll allow us to use analyzer for different schemas

**Comment by rockbruno** [comment]
You pass custom arguments to SwiftInfo and access them in the Infofile with UserDefaults 🙂Here's what I do to hide the Slack URL in the CI:

`SwiftInfo {the usual arguments} -slackurl {the url}`

```
if let slackUrl = UserDefaults.standard.string(forKey: "slackurl") {
    api.sendToSlack(output: output, webhookUrl: slackUrl)
} else {
    print("Slack Webhook URL not found!")
}
```

Does that solve your problem?

**Comment by rnkyr** [comment]
Yes, Indeed! I forgot about that trick

Thank you!
