### ISSUE TITLE
Cant find coverage report

### ISSUE THREAD

**Issue by Petteri78** [rockbruno/SwiftInfo#29]
When running test project in Xcode11 `SwiftInfo` cannot find Coverage report since log prints `Test session results, code coverage, and logs:` instead of `Code coverage report:`

**Comment by rockbruno** [comment]
Hmmm that sucks, is that always the case in Xcode 11 or running a legacy build makes it different?
Since we only support the latest Swift version, I suppose we can replace it to the new text with no side effects 🙂

**Comment by Petteri78** [comment]
I tried with legacy build and I get the same message. Is it possible to get the path in more secure way by looking at derived data path?

**Comment by Petteri78** [comment]
This is how they do in XCov.
`def parse_xccoverage
      # Find .xccoverage file
      # If no xccov direct path, use the old derived data path method
      if xccov_file_direct_paths.nil?
        extension = Xcov.config[:legacy_support] ? "xccoverage" : "xccovreport"
        test_logs_path = derived_data_path + "Logs/Test/"
        xccoverage_files = Dir["#{test_logs_path}*.#{extension}", "#{test_logs_path}*.xcresult/*/action.#{extension}"].sort_by { |filename| File.mtime(filename) }.reverse

        if xccoverage_files.empty?
          xcresult_paths = Dir["#{test_logs_path}*.xcresult"].sort_by { |filename| File.mtime(filename) }.reverse
          xcresult_paths.each do |xcresult_path|
            xccoverage_files += export_paths_from_xcresult!(xcresult_path)
          end
        end

        unless test_logs_path.directory? && !xccoverage_files.empty?
          ErrorHandler.handle_error("XccoverageFileNotFound")
        end
      else
        xccoverage_files = xccov_file_direct_paths
      end


      # Convert .xccoverage file to json
      ide_foundation_path = Xcov.config[:legacy_support] ? nil : Xcov.config[:ideFoundationPath]
      json_report = Xcov::Core::Parser.parse(xccoverage_files.first, Xcov.config[:output_directory], ide_foundation_path)
      ErrorHandler.handle_error("UnableToParseXccoverageFile") if json_report.nil?

      json_report
    end`

**Comment by Petteri78** [comment]
You could probably use a Regex like `^\/([A-z0-9-_+]+\/)*(.+\.(xcresult|xccovreport))$`

**Comment by rockbruno** [comment]
Geez, I'm trying to fix this but the cov format is now the generic `xcreport` instead of `xccovreport`. Trying to see if there's a way to get the covs from that, in the terminal.

**Comment by rockbruno** [comment]
Woohoo thanks for documentation: `xccov now supports being passed result bundles directly, in addition to raw report and archive files. For example, to view the coverage report within a result bundle, invoke xccov as follows: xccov view --report /path/to/result_bundle.xcresult. (50500789)`

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes

I'll be submitting the fix for this soon.

**Comment by rockbruno** [comment]
2.3.7 should fix this issue.

**Comment by Petteri78** [comment]
Nice work! This project is great and I would like to contribute if you need help?

**Comment by rockbruno** [comment]
Feel free to submit PRs for absolutely anything! I'm not doing anything new for it at the moment but that's because I haven't thought of anything new yet 😛

**Comment by rogerluan** [comment]
Looks like this issue was resolved :) I'm closing it 👍
