### ISSUE TITLE
module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by JulianKahnert** [rockbruno/SwiftInfo#33]
Hi @rockbruno,
thank you for this awesome project!! 🙂 👍 

I installed `swiftinfo` via Homebrew:
```bash
$ brew tap rockbruno/SwiftInfo https://github.com/rockbruno/SwiftInfo.git
$ brew install rockbruno/SwiftInfo/swiftinfo
```

When I try to run it, I am getting this error:
```bash
$ swiftinfo         
* SwiftInfo 2.3.6
./Infofile.swift:1:8: error: module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /usr/local/Cellar/swiftinfo/2.3.7/bin/../include/swiftinfo/SwiftInfoCore.swiftmodule
import SwiftInfoCore
       ^
```

I found [this](https://forums.swift.org/t/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/30431/2) where they suggest to add the `-enable-library-evolution` compiler flag. Could that be the fix?

### My System

macOS: 10.15.1 (19B88)
Xcode: Version 11.2.1 (11B53)

```bash
$ swift --version
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0
```

**Comment by rockbruno** [comment]
That's really a bummer... I would expect it to work because of module stability
I'll find out how to do use that flag with swift package manager, it should fix it :)

**Comment by rockbruno** [comment]
Can you check if the branch from this PR fixes the issue? https://github.com/rockbruno/SwiftInfo/pull/34
You can generate a new binary from that branch by running `make build` and then `make package`.

**Comment by JulianKahnert** [comment]
Hi,
first I wanted to reproduce the problem by building the master. I cloned the repo, run `make build` and `make package`.
But when I copy the contents of the zip folder in my project, I get this error:
```bash
$ swiftinfo/bin/swiftinfo
* SwiftInfo 2.3.6
SwiftInfo crashed. Reason: Failed to load .pbxproj! (./PDFArchiver.xcodeproj)
```

Now I am a little confused: can I run the binary, because I have built it on my machine or does the error occur to "early"? 🤨🤔

**Comment by rockbruno** [comment]
That's true, since you built it in your machine that's using the newest Xcode, you can run it :) The error would probably shift to me in this case as it would probably require me to use the newest xcode. Can you upload it here? if it works then we can just submit a new version with the newest xcode.

**Comment by JulianKahnert** [comment]
Hi, I checked out the `library-evolution` and run `make build`/`make package` again. This is the output:
[swiftinfo.zip](https://github.com/rockbruno/SwiftInfo/files/3869043/swiftinfo.zip)
🙂

**Comment by rockbruno** [comment]
Didn't work, I get the reverse error 😢 
`module compiled with Swift 5.1.2 cannot be imported by the Swift 5.1 compiler`
I'll try to reverse engineer what xcode does when that setting they mention in the Swift forums thread is active to see if we're missing something.

**Comment by JulianKahnert** [comment]
I just found [this Swift Homebrew arcticle](https://nshipster.com/homebrew/) by @mattt but he also just uses `swift build -c release --disable-sandbox` 🤨

**Comment by JulianKahnert** [comment]
You could rewrite the Homebrew Formula to not download the precompiled binary and instead compile it on the machine. This is done in the [SwiftLint Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/swiftlint.rb) ... it triggers the build process in the [SwiftLint Makefile](https://github.com/realm/SwiftLint/blob/master/Makefile).
That could be a first workaround ... but since Swift reached ABI stability, we don't *have* to that, right?

**Comment by taher-mosbah** [comment]
Hey guys, any update on this ? is a new version compiled with Xcode 11.2 on the roadmap ?
Thanks !

**Comment by rockbruno** [comment]
If the version is out of beta, we can deploy a new version indeed 👍

**Comment by taher-mosbah** [comment]
@rockbruno 11.2.1 is the latest stable release, 11.3 is beta for ~3 weeks now.

**Comment by JulianKahnert** [comment]
Xcode 11.3 is now stable. Any updates on the next steps? Do you want to use a Makefile like [SwiftLint](https://github.com/realm/SwiftLint/blob/master/Makefile)?

**Comment by rockbruno** [comment]
I've pushed 2.3.8, built with Xcode 11.3. It should now be fixed :)

**Comment by taher-mosbah** [comment]
Working for me, thanks 🙏

**Comment by HamzaGhazouani** [comment]
Hey, how we can use an old version with Homebrew ? (we did not migrate yet to Xcode 11.3)

**Comment by rockbruno** [comment]
I think this works: https://flaviocopes.com/homebrew-install-older-version/
You can get the formula from a previous tag and install it directly

**Comment by HamzaGhazouani** [comment]
@rockbruno I can't find swiftInfo https://github.com/Homebrew/homebrew-core/search?utf8=%E2%9C%93&q=swiftinfo&type=

**Comment by rockbruno** [comment]
The formula is not public, you're probably searching for this: https://raw.githubusercontent.com/rockbruno/SwiftInfo/2.3.7/Formula/swiftinfo.rb

**Comment by HamzaGhazouani** [comment]
thanks a lot
