### ISSUE TITLE
Xcode 12 & Swift 5.3 support

### ISSUE THREAD

**Issue by andre-alves** [rockbruno/SwiftInfo#44]
Hi Bruno 👋,

We are using Cocoapods installation option and running SwiftInfo with Xcode 12 outputs the following error:

```
* SwiftInfo 2.3.11
./Infofile.swift:1:8: error: module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler: /Users/andre.alves/i/Pods/SwiftInfo/bin/../include/swiftinfo/SwiftInfoCore.swiftmodule
import SwiftInfoCore
```

I can try to help but just releasing a new version built with Xcode 12 should probably fix the issue.

**Comment by rockbruno** [comment]
Hey André :)
I'll compile a new version and post it here. It's weird because module stability should've been fixed it many versions ago but I'm not sure why it doesn't work with command line tools

**Comment by rockbruno** [comment]
@andre-alves Pushed `2.3.12`

**Comment by andre-alves** [comment]
Thanks!
