### ISSUE TITLE
Update brew formula to 2.3.12

### ISSUE THREAD

**Issue by rowwingman** [rockbruno/SwiftInfo#46]
Brew formula used previous release 2.3.11 for xcode 11.4. Update brew formula to 2.3.12 and xcode 12

Have an error right now:
```
* SwiftInfo 2.3.11
./Infofile.swift:1:8: error: module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler: /usr/local/Cellar/swiftinfo/2.3.11/bin/../include/swiftinfo/SwiftInfoCore.swiftmodule
import SwiftInfoCore
```

**Comment by rockbruno** [comment]
Can you open a PR bumping it if you need it? I would appreciate it a lot 🙂

**Comment by rowwingman** [comment]
https://github.com/rockbruno/SwiftInfo/pull/47
