### ISSUE TITLE
Add a --version option

### ISSUE THREAD

**Issue by marcelofabri** [rockbruno/SwiftInfo#48]
SwiftInfo prints the version when running it, but it crashes if you don't have a configuration file in the current working directory:

```
~/Downloads/swiftinfo/bin/swiftinfo
* SwiftInfo 2.3.12
Fatal error: 'try!' expression unexpectedly raised an error: SwiftInfoCore.SwiftInfoError.generic("Infofile.swift not found."): file SwiftInfo/main.swift, line 15
[1]    87311 illegal hardware instruction  ~/Downloads/swiftinfo/bin/swiftinfo --version
```

It'd be great to have a `--version` option that only prints the version (and doesn't crash 😂)

**Comment by rockbruno** [comment]
There is one! It's `-version` 🙂 

Good opportunity to migrate to https://github.com/apple/swift-argument-parser as I guess this wasn't showing in the help message

**Comment by marcelofabri** [comment]
Oops 😅

I had tried `--version` and just `version`, but not `-version` 😱
