### ISSUE TITLE
Add Lines of Code (LoC) provider

### ISSUE THREAD

**Issue by Dschee** [rockbruno/SwiftInfo#5]
I think it would be useful if this also had a provider built in which reports the changes in total lines of code, maybe separated by Swift and ObjC code. It should be intelligent or configurable enough to exclude comments and dependency framework directories or generated file directories.

**Comment by rockbruno** [comment]
Good idea! The code coverage logs already provide this info so it can be easily extracted from there, although I think it would be cool if a way to extract this from the build logs was found so running tests aren't needed. I think SourceKit's editor.open may have this info.

**Comment by rockbruno** [comment]
Added in https://github.com/rockbruno/SwiftInfo/pull/6 . It considers all executable lines (so it'll consider frameworks as well, which I think it makes sense), but once I add support for arguments we'll be able to filter specific cases.

**Comment by Dschee** [comment]
I don't think considering frameworks makes sense at all in most cases. When I write an app within my team, I'm only interested the code written by us, not the frameworks integrated. Consider this situation: Somebody adds a line of code, but also updates a framework version where hundred lines of code were changed. Now the output doesn't show me at all that the developer actually only changed a single line.

So all "usual" framework directories should be excluded by default, meaning anything below the folders `Pods`, `Carthage`, `.accio` and `Dependencies`. Also `.git` should be excluded to be sure not to count any history files. Of course you could also by default exclude any hidden files, so only `Pods`, `Carthage` and `Dependencies` would be needed.

**Comment by rockbruno** [comment]
Makes sense! This will be better handled with an argument system though as it's common nowadays to have a project that is divided in several modules, so simply ignoring frameworks would bring wrong results. I think specifically mentioning the targets you want to track will bring the best results.

**Comment by Dschee** [comment]
What I'm talking about are frameworks integrated by dependency managers like CocoaPods, Carthage and Accio. If you split your project into multiple modules, then you probably don't integrate them via the `Pods`, `Carthage` or `Dependencies` folders, do you? Those are reserved for remote dependencies, not project modules. At least I haven't seen a project with this setup ...

**Comment by rockbruno** [comment]
Yup, I used local pods to divide modules in this project: https://github.com/Rapiddo/rapiddo-ios-style-guide

**Comment by Dschee** [comment]
But did your code lay within the `Pods` directory? I've already seen projects which divide their code into several directories, e.g. `MyApp-Networking`, `MyApp-UI` and `MyApp-Data` but those are not placed within the Pods directory because separating them into multiple repos didn't make much sense.

Having that said though, I agree that sometimes it can make sense to actually have multiple repos and then the code would reside within the Pods directories. But in those cases I feel like it's still better to keep track of the lines of code changes separately as those Pods can be considered a different project.

**Comment by rockbruno** [comment]
Ah you're right, they don't get copied to the pods folder. I'm working on the args system now, so you'll be able to specify which targets you want to track :)

**Comment by rockbruno** [comment]
Args added in 2.0.0, you can now ignore the irrelevant targets :)

**Comment by Dschee** [comment]
Thanks a lot, I‘ll check that out soon and report if I find any other issues. Much appreciated!
