### ISSUE TITLE
error: module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler

### ISSUE THREAD

**Issue by LemonSpike** [rockbruno/SwiftInfo#51]
I get this error when trying to run SwiftInfo:

bundler: failed to load command: fastlane (/Users/intelkasetti/.rbenv/versions/2.7.1/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command '../Pods/SwiftInfo/bin/swiftinfo' was 1 instead of 0.
../Infofile.swift:1:8: error: module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler: /Users/intelkasetti/Desktop/Work/Maldaba/root/HearMeNow/Pods/SwiftInfo/bin/../include/swiftinfo/SwiftInfoCore.swiftmodule
import SwiftInfoCore
       ^
* SwiftInfo 2.3.12

I have not specified Swift versions in the Podfile or use a post-install script since it used to work out of the box. My Pods project seems to default to using Swift 5.0 in the build settings and using Xcode 12.2. Hope you can help me out!

**Comment by rogerluan** [comment]
Hey @LemonSpike 👋 
This error tells you that you're trying to use SwiftInfo (that was compiled under Swift 5.3), using Swift 5.3.1. Although you may not be specifying Swift 5.3.1 anywhere in your code, if you're using Xcode 12.2, that's the Swift version that it will use if you're specifying Swift 5 in the build settings.

Until we re-build SwiftInfo using Swift 5.3.1, it's not compatible with Xcode 12.2 unfortunately 😬 

@rockbruno what's the game plan to support multiple Swift versions in this case? Different branches for each Swift version, while master uses the latest?

**Comment by rockbruno** [comment]
I need to push a version for the newest Xcode version, will do it shortly. This is supposed to be solved with Swift's module stability but we don't know yet why it doesn't work for CLI tools...

**Comment by rogerluan** [comment]
@rockbruno does that mean you'll be officially sunsetting support to Swift 5.3 (thus requiring Xcode 12.2 for everyone)?

**Comment by rockbruno** [comment]
Yes. But this time I'll try to add the interface files alongside the binary, maybe this is why module stability isn't working.

**Comment by rockbruno** [comment]
Pushed 2.3.13
