### ISSUE TITLE
SwiftInfo on Bazel Build system

### ISSUE THREAD

**Issue by sanju-naik** [rockbruno/SwiftInfo#79]
We had this tool Integrated and it depends on Fastlane. We are migrating to the Bazel build system so was wondering is there a way to make this tool work with Bazel?

**Comment by rockbruno** [comment]
Yes, you can make it work with anything. It doesn't depend on Fastlane, it's just the main example of the repo.

**Comment by sanju-naik** [comment]
I was able to make this work with Bazel build logs. Thank you! 

Closing this issue.
